parsers:
  doc_parser:
    engine: "pandoc"
    langs: ["en", "zh"]
  docx_parser:
    engine: "pandoc"
    langs: ["en", "zh"]
  epub_parser:
    engine: "unstructured"
    langs: ["en", "zh"]
  html_parser:
    engine: "unstructured"
    langs: ["en", "zh"]
  url_parser:
    engine: "jina"
    langs: ["en", "zh"]
  pdf_parser:
    engine: "marker"
    langs: ["en", "zh"]
  pptx_parser:
    engine: "unstructured"
    langs: ["en", "zh"]
  voice_parser:
    # Option 1: Use OpenAI Whisper API
    # engine: "openai_whisper_api"
    # api_base: "https://api.openai.com/v1"
    # api_key: "your_api_key"
    # model: "whisper"
    # Option 2: Use local Whisper model
    engine: "openai_whisper_local"
    model: "large"  # Available models: https://github.com/openai/whisper#available-models-and-languages

converters:
  text_converter:
    engine: "litellm"
    model: "deepseek/deepseek-chat"
    api_key: "your_api_key"
  image_converter:
    engine: "litellm"
    model: "gpt-4o-mini"
    api_key: "your_api_key"
